version: "2.3"
services: 
  ros_master:
    build: .
    container_name: ros_master
    command: roscore

  gazebo:
    build: .
    container_name: gazebo
    command: roslaunch --wait gazebo_factory_world factory_world.launch
    runtime: nvidia
    environment: 
      - ROS_HOSTNAME=gazebo
      - ROS_MASTER_URI=http://ros_master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
  
  spawn_robots:
    build: .
    container_name: spawn_robots
    command: roslaunch --wait moving_object_simulator gazebo_simulation_spawn_robots.launch
    environment:
      - ROS_HOSTNAME=spawn_robots
      - ROS_MASTER_URI=http://ros_master:11311
    devices: 
      - /dev/input/js0:/dev/input/js0
